# Generated by Django 5.1.7 on 2025-04-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticaweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministracionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('colaborador', 'Colaborador')], max_length=20)),
            ],
        ),
    ]
