# Generated by Django 5.1.7 on 2025-04-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticaweb', '0005_producto_cantidad_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
