# Generated by Django 5.1.7 on 2025-04-19 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opticaweb', '0006_alter_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
    ]
