# Generated by Django 5.1.7 on 2025-04-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticaweb', '0008_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='consejos/')),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
