# Generated by Django 5.1.7 on 2025-04-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opticaweb', '0011_consejo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consejo',
            name='imagen',
        ),
    ]
