# Generated by Django 5.1.7 on 2025-04-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticaweb', '0012_remove_consejo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='consejo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='consejos/'),
        ),
    ]
