# Generated by Django 5.1.7 on 2025-05-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticaweb', '0015_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='rechazada',
            field=models.BooleanField(default=False),
        ),
    ]
